// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom codierten UI-Testbuilder generiert.
//      Version: 11.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      codierten UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TakingSnapShot
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Verwenden Sie "RecordedMethod1Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinButton uIProbeControllerButton = this.UISOPATStartupWindow.UIProbeControllerWindow.UIProbeControllerButton;
            WinMenuItem uISaveSnapshotMenuItem = this.UIProbeControlWindow.UIMenuStrip1MenuBar.UIActionsMenuItem.UISaveSnapshotMenuItem;
            WinCell uIEmulatedCell = this.UIProbeControlWindow.UIDataGridView1Window.UIDataGridViewTable.UIRow0Row.UIEmulatedCell;
            WinButton uIToolStripButtonConneButton = this.UIProbeControlWindow.UIToolStrip1Window.UIToolStripButtonConneButton;
            WinButton uICloseButton = this.UIEmulatedEMU0CoutputsWindow.UIEmulatedEMU0CoutputsTitleBar.UICloseButton;
            WinButton uICloseButton1 = this.UIProbeControlWindow.UIProbeControlTitleBar.UICloseButton;
            WinButton uICloseButton2 = this.UISOPATStartupWindow.UISOPATStartupTitleBar.UICloseButton;
            #endregion

            // "%ProgramW6432%\SOPAT GmbH\Dashboard\bin\startup\SOPAT_Startup.exe" starten
            ApplicationUnderTest uISOPATStartupWindow = ApplicationUnderTest.Launch(this.RecordedMethod1Params.UISOPATStartupWindowExePath, this.RecordedMethod1Params.UISOPATStartupWindowAlternateExePath);

            // Klicken "Probe Controller" Schaltfläche
            Mouse.Click(uIProbeControllerButton, new Point(43, 11));

            // Klicken "Actions" -> "Save Snapshot" Menüelement
            Mouse.Click(uISaveSnapshotMenuItem, new Point(63, 8));

            // Klicken "Actions" -> "Save Snapshot" Menüelement
            Mouse.Click(uISaveSnapshotMenuItem, new Point(59, 13));

            // Klicken "Emulated" Zelle
            Mouse.Click(uIEmulatedCell, new Point(38, 8));

            // Klicken "toolStripButtonConnect" Schaltfläche
            Mouse.Click(uIToolStripButtonConneButton, new Point(14, 7));

            // Klicken "Actions" -> "Save Snapshot" Menüelement
            Mouse.Click(uISaveSnapshotMenuItem, new Point(56, 13));

            // Klicken "Close" Schaltfläche
            Mouse.Click(uICloseButton, new Point(27, 18));

            // Klicken "Close" Schaltfläche
            Mouse.Click(uICloseButton1, new Point(26, 14));

            // Klicken "Close" Schaltfläche
            Mouse.Click(uICloseButton2, new Point(17, 25));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UISOPATStartupWindow UISOPATStartupWindow
        {
            get
            {
                if ((this.mUISOPATStartupWindow == null))
                {
                    this.mUISOPATStartupWindow = new UISOPATStartupWindow();
                }
                return this.mUISOPATStartupWindow;
            }
        }
        
        public UIProbeControlWindow UIProbeControlWindow
        {
            get
            {
                if ((this.mUIProbeControlWindow == null))
                {
                    this.mUIProbeControlWindow = new UIProbeControlWindow();
                }
                return this.mUIProbeControlWindow;
            }
        }
        
        public UIEmulatedEMU0CoutputsWindow UIEmulatedEMU0CoutputsWindow
        {
            get
            {
                if ((this.mUIEmulatedEMU0CoutputsWindow == null))
                {
                    this.mUIEmulatedEMU0CoutputsWindow = new UIEmulatedEMU0CoutputsWindow();
                }
                return this.mUIEmulatedEMU0CoutputsWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UISOPATStartupWindow mUISOPATStartupWindow;
        
        private UIProbeControlWindow mUIProbeControlWindow;
        
        private UIEmulatedEMU0CoutputsWindow mUIEmulatedEMU0CoutputsWindow;
        #endregion
    }
    
    /// <summary>
    /// An "RecordedMethod1" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// "%ProgramW6432%\SOPAT GmbH\Dashboard\bin\startup\SOPAT_Startup.exe" starten
        /// </summary>
        public string UISOPATStartupWindowExePath = "C:\\Program Files\\SOPAT GmbH\\Dashboard\\bin\\startup\\SOPAT_Startup.exe";
        
        /// <summary>
        /// "%ProgramW6432%\SOPAT GmbH\Dashboard\bin\startup\SOPAT_Startup.exe" starten
        /// </summary>
        public string UISOPATStartupWindowAlternateExePath = "%ProgramW6432%\\SOPAT GmbH\\Dashboard\\bin\\startup\\SOPAT_Startup.exe";
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UISOPATStartupWindow : WinWindow
    {
        
        public UISOPATStartupWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SOPAT - Startup";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("SOPAT - Startup");
            #endregion
        }
        
        #region Properties
        public UIProbeControllerWindow UIProbeControllerWindow
        {
            get
            {
                if ((this.mUIProbeControllerWindow == null))
                {
                    this.mUIProbeControllerWindow = new UIProbeControllerWindow(this);
                }
                return this.mUIProbeControllerWindow;
            }
        }
        
        public UISOPATStartupTitleBar UISOPATStartupTitleBar
        {
            get
            {
                if ((this.mUISOPATStartupTitleBar == null))
                {
                    this.mUISOPATStartupTitleBar = new UISOPATStartupTitleBar(this);
                }
                return this.mUISOPATStartupTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIProbeControllerWindow mUIProbeControllerWindow;
        
        private UISOPATStartupTitleBar mUISOPATStartupTitleBar;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIProbeControllerWindow : WinWindow
    {
        
        public UIProbeControllerWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "buttonProbeViewer";
            this.WindowTitles.Add("SOPAT - Startup");
            #endregion
        }
        
        #region Properties
        public WinButton UIProbeControllerButton
        {
            get
            {
                if ((this.mUIProbeControllerButton == null))
                {
                    this.mUIProbeControllerButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIProbeControllerButton.SearchProperties[WinButton.PropertyNames.Name] = "Probe Controller";
                    this.mUIProbeControllerButton.WindowTitles.Add("SOPAT - Startup");
                    #endregion
                }
                return this.mUIProbeControllerButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIProbeControllerButton;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UISOPATStartupTitleBar : WinTitleBar
    {
        
        public UISOPATStartupTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.WindowTitles.Add("SOPAT - Startup");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("SOPAT - Startup");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIProbeControlWindow : WinWindow
    {
        
        public UIProbeControlWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ProbeControl";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ProbeControl");
            #endregion
        }
        
        #region Properties
        public UIMenuStrip1MenuBar UIMenuStrip1MenuBar
        {
            get
            {
                if ((this.mUIMenuStrip1MenuBar == null))
                {
                    this.mUIMenuStrip1MenuBar = new UIMenuStrip1MenuBar(this);
                }
                return this.mUIMenuStrip1MenuBar;
            }
        }
        
        public UIDataGridView1Window UIDataGridView1Window
        {
            get
            {
                if ((this.mUIDataGridView1Window == null))
                {
                    this.mUIDataGridView1Window = new UIDataGridView1Window(this);
                }
                return this.mUIDataGridView1Window;
            }
        }
        
        public UIToolStrip1Window UIToolStrip1Window
        {
            get
            {
                if ((this.mUIToolStrip1Window == null))
                {
                    this.mUIToolStrip1Window = new UIToolStrip1Window(this);
                }
                return this.mUIToolStrip1Window;
            }
        }
        
        public UIProbeControlTitleBar UIProbeControlTitleBar
        {
            get
            {
                if ((this.mUIProbeControlTitleBar == null))
                {
                    this.mUIProbeControlTitleBar = new UIProbeControlTitleBar(this);
                }
                return this.mUIProbeControlTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIMenuStrip1MenuBar mUIMenuStrip1MenuBar;
        
        private UIDataGridView1Window mUIDataGridView1Window;
        
        private UIToolStrip1Window mUIToolStrip1Window;
        
        private UIProbeControlTitleBar mUIProbeControlTitleBar;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIMenuStrip1MenuBar : WinMenuBar
    {
        
        public UIMenuStrip1MenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinMenu.PropertyNames.Name] = "menuStrip1";
            this.WindowTitles.Add("ProbeControl");
            #endregion
        }
        
        #region Properties
        public UIActionsMenuItem UIActionsMenuItem
        {
            get
            {
                if ((this.mUIActionsMenuItem == null))
                {
                    this.mUIActionsMenuItem = new UIActionsMenuItem(this);
                }
                return this.mUIActionsMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIActionsMenuItem mUIActionsMenuItem;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIActionsMenuItem : WinMenuItem
    {
        
        public UIActionsMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Actions";
            this.WindowTitles.Add("ProbeControl");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UISaveSnapshotMenuItem
        {
            get
            {
                if ((this.mUISaveSnapshotMenuItem == null))
                {
                    this.mUISaveSnapshotMenuItem = new WinMenuItem(this);
                    #region Suchkriterien
                    this.mUISaveSnapshotMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Save Snapshot";
                    this.mUISaveSnapshotMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUISaveSnapshotMenuItem.WindowTitles.Add("ProbeControl");
                    #endregion
                }
                return this.mUISaveSnapshotMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUISaveSnapshotMenuItem;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIDataGridView1Window : WinWindow
    {
        
        public UIDataGridView1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dataGridView1";
            this.WindowTitles.Add("ProbeControl");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("ProbeControl");
            #endregion
        }
        
        #region Properties
        public UIRow0Row UIRow0Row
        {
            get
            {
                if ((this.mUIRow0Row == null))
                {
                    this.mUIRow0Row = new UIRow0Row(this);
                }
                return this.mUIRow0Row;
            }
        }
        #endregion
        
        #region Fields
        private UIRow0Row mUIRow0Row;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIRow0Row : WinRow
    {
        
        public UIRow0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinRow.PropertyNames.Value] = "Emulated;EMU-0;System.Drawing.Bitmap;System.Drawing.Bitmap;System.Drawing.Bitmap";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("ProbeControl");
            #endregion
        }
        
        #region Properties
        public WinCell UIEmulatedCell
        {
            get
            {
                if ((this.mUIEmulatedCell == null))
                {
                    this.mUIEmulatedCell = new WinCell(this);
                    #region Suchkriterien
                    this.mUIEmulatedCell.SearchProperties[WinCell.PropertyNames.Value] = "Emulated";
                    this.mUIEmulatedCell.WindowTitles.Add("ProbeControl");
                    #endregion
                }
                return this.mUIEmulatedCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIEmulatedCell;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIToolStrip1Window : WinWindow
    {
        
        public UIToolStrip1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "toolStrip1";
            this.WindowTitles.Add("ProbeControl");
            #endregion
        }
        
        #region Properties
        public WinButton UIToolStripButtonConneButton
        {
            get
            {
                if ((this.mUIToolStripButtonConneButton == null))
                {
                    this.mUIToolStripButtonConneButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUIToolStripButtonConneButton.SearchProperties[WinButton.PropertyNames.Name] = "toolStripButtonConnect";
                    this.mUIToolStripButtonConneButton.WindowTitles.Add("ProbeControl");
                    #endregion
                }
                return this.mUIToolStripButtonConneButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIToolStripButtonConneButton;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIProbeControlTitleBar : WinTitleBar
    {
        
        public UIProbeControlTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.WindowTitles.Add("ProbeControl");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("ProbeControl");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIEmulatedEMU0CoutputsWindow : WinWindow
    {
        
        public UIEmulatedEMU0CoutputsWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Emulated - EMU-0 C:\\output\\snapshot_11-28-36-232.bmp - 1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Emulated - EMU-0 C:\\output\\snapshot_11-28-36-232.bmp - 1");
            #endregion
        }
        
        #region Properties
        public UIEmulatedEMU0CoutputsTitleBar UIEmulatedEMU0CoutputsTitleBar
        {
            get
            {
                if ((this.mUIEmulatedEMU0CoutputsTitleBar == null))
                {
                    this.mUIEmulatedEMU0CoutputsTitleBar = new UIEmulatedEMU0CoutputsTitleBar(this);
                }
                return this.mUIEmulatedEMU0CoutputsTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIEmulatedEMU0CoutputsTitleBar mUIEmulatedEMU0CoutputsTitleBar;
        #endregion
    }
    
    [GeneratedCode("Test-Generator für codierte UI", "11.0.50727.1")]
    public class UIEmulatedEMU0CoutputsTitleBar : WinTitleBar
    {
        
        public UIEmulatedEMU0CoutputsTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.WindowTitles.Add("Emulated - EMU-0 C:\\output\\snapshot_11-28-36-232.bmp - 1");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Emulated - EMU-0 C:\\output\\snapshot_11-28-36-232.bmp - 1");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
